<%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib uri="/WEB-INF/struts-html.tld" prefix="html" %>
<%@ taglib uri="/WEB-INF/struts-tiles.tld" prefix="tiles" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/fmt" prefix="fmt" %>
<%@ taglib tagdir="/WEB-INF/tags" prefix="im" %>


<div class="body">
  <im:boxarea title="Data" stylename="plainbox" >
    Phycomine integrates data from several sources into a single data warehouse. This page lists the data and sources that are included in the current release.
  </im:boxarea>


  <div class="phycomineDataSources">
    <h3>The following data are loaded in Phycomine:</h3>
    <table cellpadding="0" cellspacing="0" border="0" class="dbsources">
      <thead>
        <th><h2>Data Category</h2></th>
        <th><h2>Organism</h2></th>
        <th><h2>Data</h2></th>
        <th><h2>Source</h2></th>
      </thead>
      <tbody>
        <tr>
          <td rowspan="2" class="leftcol"><h2>GENOME</h2></td>
          <td>Chlamydomonas reinhardtii</td>
          <td>Chlamydomonas reinhardtii genome information: sequences and annotations.</td>
          <td><a href="https://phytozome.jgi.doe.gov">Phytozome</a></td>
        </tr>
        <tr>
          <td>Chlorella vulgaris</td>
          <td>Chlorella vulgaris genome information: sequences and annotations.</td>
          <td><a href="http://chlorella.genomeprojectsolutions-databases.com/">Genome Project Solutions databases</a></td>
        </tr>

        <tr>
          <td rowspan="2" class="leftcol"><h2>PROTEINS</h2></td>
          <td>Chlamydomonas reinhardtii</td>
          <td>Protein sequence and annotation of Chlamydomonas reinhardtii (3055).</td>
          <td><a href="https://www.uniprot.org">Uniprot</a></td>
        </tr>
        <tr>
          <td>Chlorella vulgaris</td>
          <td>Protein sequence and annotation of Chlorella vulgaris (3077).</td>
          <td><a href="https://www.uniprot.org">Uniprot</a></td>
        </tr>

        <tr>
          <td rowspan="2" class="leftcol"><h2>GENE ONTOLOGY</h2></td>
          <td>Chlamydomonas reinhardtii</td>
          <td>Chlamydomonas reinhardtii Gene ontology annotations.</td>
          <td><a href="http://www3.iq.usp.br/pessoas_view.php?idDocente=468">Labis</a></td>
        </tr>
        <tr>
          <td>Chlorella vulgaris</td>
          <td>Chlorella vulgaris Gene ontology annotations.</td>
          <td><a href="http://www3.iq.usp.br/pessoas_view.php?idDocente=468">Labis</a></td>
        </tr>

        <tr>
          <td rowspan="2" class="leftcol"><h2>PATHWAYS</h2></td>
          <td>Chlamydomonas reinhardtii</td>
          <td>Gene-pathway for Chlamydomonas reinhardtii annotations from Kegg.</td>
          <td><a href="http://www3.iq.usp.br/pessoas_view.php?idDocente=468">Labis</a></td>
        </tr>
        <tr>
          <td>Chlorella vulgaris</td>
          <td>Gene-pathway for Chlorella vulgaris annotations from Kegg.</td>
          <td><a href="http://www3.iq.usp.br/pessoas_view.php?idDocente=468">Labis</a></td>
        </tr>

        <tr>
          <td rowspan="4" class="leftcol"><h2>GENE FAMILIES</h2></td>
          <td rowspan="2">Chlamydomonas reinhardtii</td>
          <td>Chlamydomonas reinhardtii Gene families annotations from EggNog.</td>
          <td><a href="http://www3.iq.usp.br/pessoas_view.php?idDocente=468">Labis</a></td>
        </tr>
        <tr>
          <td>Chlamydomonas reinhardtii Gene families annotations from PlnTFDB.</td>
          <td><a href="http://www3.iq.usp.br/pessoas_view.php?idDocente=468">Labis</a></td>
        </tr>

        <tr>
          <td rowspan="2">Chlorella vulgaris</td>
          <td>Chlorella vulgaris Gene families annotations from EggNog.</td>
          <td><a href="http://www3.iq.usp.br/pessoas_view.php?idDocente=468">Labis</a></td>
        </tr>
        <tr>
          <td>Chlorella vulgaris Gene families annotations from PlnTFDB.</td>
          <td><a href="http://www3.iq.usp.br/pessoas_view.php?idDocente=468">Labis</a></td>
        </tr>

        <tr>
          <td rowspan="2" class="leftcol"><h2>GENOMIC PROTEINS</h2></td>
          <td>Chlamydomonas reinhardtii</td>
          <td>Sequences and annotations of Proteins for Chlamydomonas reinhardtii.</td>
          <td><a href="https://phytozome.jgi.doe.gov">Phytozome</a></td>
        </tr>
        <tr>
          <td>Chlorella vulgaris</td>
          <td>Sequences and annotations of Proteins Generated by Gff Read software, based in the genome annotations of Chlorella vulgaris.</td>
          <td><a href="http://chlorella.genomeprojectsolutions-databases.com/">Genome Project Solutions databases</a></td>
        </tr>

        <tr>
          <td class="leftcol"><h2>ORTHOLOGS</h2></td>
          <td>Chlamydomonas reinhardtii, Chlorella vulgaris</td>
          <td>Orthologs groups generated by Ortho Finder with the protein sequences of Chlamydomonas reinhardtii and Chlorella vulgaris.</td>
          <td><a href="http://www3.iq.usp.br/pessoas_view.php?idDocente=468">Labis</a></td>
        </tr>

        <tr>
          <td class="leftcol"><h2>EXPRESSIONS</h2></td>
          <td>Chlamydomonas reinhardtii, Chlorella vulgaris</td>
          <td>RNA-Seq information downloaded from NCBI (<im:querylink text="Papers Downloaded" skipBuilder="true">
                                                          <query model="genomic" view="Publication.pubMedId Publication.experimentDescription.name" sortOrder="Publication.pubMedId ASC" ></query>
                                                        </im:querylink>), and processed with bbduk, salmon and tximport.</td>
          <td><a href="http://www3.iq.usp.br/pessoas_view.php?idDocente=468">Labis</a></td>
        </tr>

         <tr>
          <td class="leftcol"><h2>PUBLICATIONS</h2></td>
          <td>Chlamydomonas reinhardtii, Chlorella vulgaris</td>
          <td>Publications of the expressions and the genes from NCBI PubMed data base.</td>
          <td><a href="https://www.ncbi.nlm.nih.gov/pubmed">NCBI</a></td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

<link rel="stylesheet" href="model/style/dataSources.css">

